spring:
  application:
    name: Pigeon-API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pigeon-server-ubuntu:3306/pigeonsource
    username: root
    password: Htc0319@2004
  data:
    redis:
      host: pigeon-server-ubuntu
      port: 6379
      password: Htc0319@2004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:65511/eureka
server:
  port: 65509
management:
  endpoints:
    web:
      exposure:
        include: '*'
user:
  api-config-id: 1